### ISSUE TITLE
Polyfill WebSerial with WebUSB for Mobile devices

### ISSUE THREAD

**Issue by archef2000** [espressif/vscode-esp-idf-web-extension#6]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Described the feature in detail and justified the reason for the request.
- [X] Provided specific use cases and examples.

### Feature description

Mobile Android browsers/devices only support WebUSB and so esp-idf-web is currently incompatible with them. VSCode Web also supports USB access so it could be polyfilled.

### Use cases

Use code server with a low power Android device.

### Additional context

I was already working on the polyfill with the libary from google, but now I will have to change it a bit.

Would you accept a PR?

**Comment by brianignacio5** [comment]
Yeah sure thing, thanks !
